### ISSUE TITLE
missing dashbord

### ISSUE THREAD

**Issue by mbiombani** [cnstlungu/portable-data-stack-airflow#1]
Hello, I can't find the dashbord.json file in the superset folder

**Comment by cnstlungu** [comment]
Hi, thanks for reaching out @mbiombani.  It is indeed missing.

Looks like in the current version of Superset the import/export is using a zip archive rather than a json. Tried exporting/importing it but it errors out with a message similar to https://github.com/apache/superset/issues/8538.

I've taken out the commands related to the importing the dashboard so the project can build successfully.

**Comment by mbiombani** [comment]
Please send me the dashboard by email

**Comment by cnstlungu** [comment]
dashboard added
